STATE_BEGIN = 0
STATE_FINISH = -1
STATE_ERROR = -2

STATE_SELECT_QUEST = 1
STATE_SELECT_TEAM = 2
STATE_APPLY_TEAM_CONFIG = 3
STATE_ENTER_QUEST = 4
STATE_BATTLE_LOOP = 5
STATE_EXIT_QUEST = 6
# STATE_CHECK_AP = 7
STATE_CHECK_EAT_APPLE = 8
STATE_SELECT_SUPPORT = 9

# Continuous battle introduced in Sep 2020 (CN server)
STATE_CONTINUOUS_BATTLE_CONFIRM = 10
STATE_CONTINUOUS_SELECT_SUPPORT = 11
